### ISSUE TITLE
unable to use operator in-cluster (x509: certificate signed by unknown authority)

### ISSUE THREAD

**Issue by kadel** [janus-idp/backstage-operator#30]
### Describe the bug

When running operator in cluster I get the following errors 
```
 status:
    conditions:
    - lastTransitionTime: "2023-10-13T13:38:01Z"
      status: "False"
      type: Deployed
    - lastTransitionTime: "2023-10-13T13:38:01Z"
      status: "True"
      type: Initialized
    - lastTransitionTime: "2023-10-13T13:38:26Z"
      message: |-
        values don't meet the specifications of the schema(s) in the following chart(s):
        upstream:
        Get "https://raw.githubusercontent.com/bitnami/charts/main/bitnami/postgresql/values.schema.json": x509: certificate signed by unknown authority
      reason: ReconcileError
      status: "True"
      type: Irreconcilable
    - lastTransitionTime: "2023-10-13T13:38:01Z"
      message: |-
        values don't meet the specifications of the schema(s) in the following chart(s):
        upstream:
        Get "https://raw.githubusercontent.com/bitnami/charts/main/bitnami/postgresql/values.schema.json": x509: certificate signed by unknown authority
      reason: InstallError
      status: "True"
      type: ReleaseFailed
```

### What are the steps to reproduce this bug?

1. build and push operator, bundle and catalog images
2. add CatalogSource 
3. create a backstage instance using [sample](https://github.com/janus-idp/backstage-operator/blob/main/config/samples/charts_v1alpha1_backstage.yaml) 

### Versions of software used and environment
tested on crc and 4.13 cluster on GCP both with the same problem
